Repository cnpm/cnpmjs.org, pull requests merged in 2019-02, with the labels that each got.

#1436 feat: support customized middlewares
  config/index.js
  servers/registry.js
  test/controllers/registry/package/list.test.js
Labels: in progress

#1438 fix: avoid toString as downloads count key
  controllers/registry/package/download.js
Labels: bug, in progress

#1441 feat: add redis cache to import list all versions api perf
  common/cache.js
  common/urllib.js
  config/index.js
  controllers/registry/package/list.js
  controllers/sync_module_worker.js
  package.json
Labels: feat, in progress, perf
