Repository cnpm/cnpmjs.org, pull requests merged in 2021-11, with the labels that each got.

#1674 Fix/rebuild
  controllers/utils.js
Labels: bug

#1675 refactor: use remote abbreviated version data
  Dockerfile
  README.md
  config/index.js
  controllers/registry/package/list.js
  controllers/sync_module_worker.js
  docs/dockerize/config.js
  docs/network.puml
  docs/web/readme.md
  services/package.js
  test/controllers/sync_module_worker.test.js
  test/fixtures/scope-package/Makefile
  test/mocks/package/koa/default.js
Labels: feat

#1677 feat: support dist.integrity
  .github/workflows/nodejs.yml
  controllers/registry/package/save.js
  controllers/sync_module_worker.js
  package.json
  test/controllers/registry/package/list.test.js
  test/controllers/registry/package/save.test.js
  test/controllers/sync_module_worker.test.js
Labels: feat

#1682 refactor: dist tarbar url don't contains querystring
  lib/common.js
  test/common/urllib.test.js
  test/controllers/registry/package/list.test.js
  test/controllers/registry/package/show.test.js
Labels: bug, feat

#1684 feat: support bug-versions on server
  .github/workflows/nodejs.yml
  config/index.js
  controllers/registry/package/download.js
  controllers/registry/package/list.js
  controllers/sync_module_worker.js
  lib/common.js
  services/bug_version.js
  test/controllers/registry/package/list.test.js
Labels: feat

#1685 fix: add missing config property for bug-versions
  services/bug_version.js
  test/controllers/registry/package/list.test.js
Labels: bug
